image: docker:stable

stages:
  - build-temporary-docker-image
  - tag-and-push-image

variables:
  TEMP_IMAGE_NAME: $CI_REGISTRY_IMAGE/ci/watchtower-gitlab-deploy:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

build temporary image:
  stage: build-temporary-docker-image
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f Dockerfile -t $TEMP_IMAGE_NAME .
    - docker push $TEMP_IMAGE_NAME

tag and publish docker image:
  stage: tag-and-push-image
  variables:
    DEFINITIVE_IMAGE_NAME: victorcmoura/watchtower-gitlab-deploy:latest
    GIT_STRATEGY: none
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker pull $TEMP_IMAGE_NAME
    - docker tag $TEMP_IMAGE_NAME $DEFINITIVE_IMAGE_NAME
    - docker push $DEFINITIVE_IMAGE_NAME
  only:
    - master